# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wipe_pedigrees <- function(pedigrees) {
    invisible(.Call('_pedinf_wipe_pedigrees', PACKAGE = 'pedinf', pedigrees))
}

#' Build pedigrees
#' 
#' @export
build_pedigrees_recursive <- function(population, progress = TRUE) {
    .Call('_pedinf_build_pedigrees_recursive', PACKAGE = 'pedinf', population, progress)
}

#' Build pedigrees
#' 
#' @export
build_pedigrees_iterative <- function(population, progress = TRUE) {
    .Call('_pedinf_build_pedigrees_iterative', PACKAGE = 'pedinf', population, progress)
}

#' Build maternal pedigrees
#' 
#' @export
build_maternal_pedigrees_recursive <- function(population, progress = TRUE) {
    .Call('_pedinf_build_maternal_pedigrees_recursive', PACKAGE = 'pedinf', population, progress)
}

wipe_population <- function(population) {
    invisible(.Call('_pedinf_wipe_population', PACKAGE = 'pedinf', population))
}

#' Construct a population
#' 
#' @export
load_individuals <- function(pid, is_male, pid_mom, pid_dad, progress = TRUE, error_on_pid_not_found = TRUE) {
    .Call('_pedinf_load_individuals', PACKAGE = 'pedinf', pid, is_male, pid_mom, pid_dad, progress, error_on_pid_not_found)
}

pedinf_test <- function() {
    invisible(.Call('_pedinf_pedinf_test', PACKAGE = 'pedinf'))
}

pop_size <- function(population) {
    .Call('_pedinf_pop_size', PACKAGE = 'pedinf', population)
}

#' Get number of pedigrees
#' 
#' @export
pedigrees_count <- function(pedigrees) {
    .Call('_pedinf_pedigrees_count', PACKAGE = 'pedinf', pedigrees)
}

#' Get pedigree size
#' 
#' @export
pedigree_size <- function(ped) {
    .Call('_pedinf_pedigree_size', PACKAGE = 'pedinf', ped)
}

#' Get distribution of pedigree sizes
#' 
#' @export
pedigrees_table <- function(pedigrees) {
    .Call('_pedinf_pedigrees_table', PACKAGE = 'pedinf', pedigrees)
}

get_pedigree <- function(pedigrees, index) {
    .Call('_pedinf_get_pedigree', PACKAGE = 'pedinf', pedigrees, index)
}

get_individual <- function(population, pid) {
    .Call('_pedinf_get_individual', PACKAGE = 'pedinf', population, pid)
}

print_individual <- function(individual) {
    invisible(.Call('_pedinf_print_individual', PACKAGE = 'pedinf', individual))
}

get_children_count <- function(individual) {
    .Call('_pedinf_get_children_count', PACKAGE = 'pedinf', individual)
}

print_pedigree <- function(ped) {
    invisible(.Call('_pedinf_print_pedigree', PACKAGE = 'pedinf', ped))
}

#' get pids in pedigree
#' 
#' @export
get_pids_in_pedigree <- function(ped) {
    .Call('_pedinf_get_pids_in_pedigree', PACKAGE = 'pedinf', ped)
}

get_pedigree_edgelist <- function(ped) {
    .Call('_pedinf_get_pedigree_edgelist', PACKAGE = 'pedinf', ped)
}

#' Get pedigree information as graph (mainly intended for plotting)
#' 
#' @export
get_pedigree_as_graph <- function(ped) {
    .Call('_pedinf_get_pedigree_as_graph', PACKAGE = 'pedinf', ped)
}

#' Get pedigree from individual
#' 
#' @export
get_pedigree_from_individual <- function(individual) {
    .Call('_pedinf_get_pedigree_from_individual', PACKAGE = 'pedinf', individual)
}

#' Get pedigree id from pid
#' 
#' @export
get_pedigree_id_from_pid <- function(population, pids) {
    .Call('_pedinf_get_pedigree_id_from_pid', PACKAGE = 'pedinf', population, pids)
}

#' Get pedigree id from pid
#' 
#' @export
get_pedigree_size_from_pid <- function(population, pids) {
    .Call('_pedinf_get_pedigree_size_from_pid', PACKAGE = 'pedinf', population, pids)
}

#' Get pedigree id from pedigree
#' 
#' @export
get_pedigree_id_from_pedigree <- function(ped) {
    .Call('_pedinf_get_pedigree_id_from_pedigree', PACKAGE = 'pedinf', ped)
}

#' Build pedigrees
#' 
#' @export
number_of_singletons <- function(population) {
    .Call('_pedinf_number_of_singletons', PACKAGE = 'pedinf', population)
}

